In [1]:
import os
import pandas as pd

In [30]:
data = pd.read_parquet('cicevse_network.parquet')

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482309 entries, 0 to 482308
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            482309 non-null  int64
 1   expiration_id                 482309 non-null  int64
 2   src_ip                        482309 non-null  object
 3   src_mac                       482309 non-null  object
 4   src_oui                       482309 non-null  object
 5   src_port                      482309 non-null  int64
 6   dst_ip                        482309 non-null  object
 7   dst_mac                       482309 non-null  object
 8   dst_oui                       482309 non-null  object
 9   dst_port                      482309 non-null  int64
 10  protocol                      482309 non-null  int64
 11  ip_version                    482309 non-null  int64
 12  vlan_id                       482309 non-null  int64
 13  tunnel_id                     482309 non-null  int64
 14  bidirectional_first_seen_ms   482309 non-null  int64
 15  bidirectional_last_seen_ms    482309 non-null  int64
 16  bidirectional_duration_ms     482309 non-null  int64
 17  bidirectional_packets         482309 non-null  int64
 18  bidirectional_bytes           482309 non-null  int64
 19  src2dst_first_seen_ms         482309 non-null  int64
 20  src2dst_last_seen_ms          482309 non-null  int64
 21  src2dst_duration_ms           482309 non-null  int64
 22  src2dst_packets               482309 non-null  int64
 23  src2dst_bytes                 482309 non-null  int64
 24  dst2src_first_seen_ms         482309 non-null  int64
 25  dst2src_last_seen_ms          482309 non-null  int64
 26  dst2src_duration_ms           482309 non-null  int64
 27  dst2src_packets               482309 non-null  int64
 28  dst2src_bytes                 482309 non-null  int64
 29  bidirectional_min_ps          482309 non-null  int64
 30  bidirectional_mean_ps         482309 non-null  float64
 31  bidirectional_stddev_ps       482309 non-null  float64
 32  bidirectional_max_ps          482309 non-null  int64
 33  src2dst_min_ps                482309 non-null  int64
 34  src2dst_mean_ps               482309 non-null  float64
 35  src2dst_stddev_ps             482309 non-null  float64
 36  src2dst_max_ps                482309 non-null  int64
 37  dst2src_min_ps                482309 non-null  int64
 38  dst2src_mean_ps               482309 non-null  float64
 39  dst2src_stddev_ps             482309 non-null  float64
 40  dst2src_max_ps                482309 non-null  int64
 41  bidirectional_min_piat_ms     482309 non-null  int64
 42  bidirectional_mean_piat_ms    482309 non-null  float64
 43  bidirectional_stddev_piat_ms  482309 non-null  float64
 44  bidirectional_max_piat_ms     482309 non-null  int64
 45  src2dst_min_piat_ms           482309 non-null  int64
 46  src2dst_mean_piat_ms          482309 non-null  float64
 47  src2dst_stddev_piat_ms        482309 non-null  float64
 48  src2dst_max_piat_ms           482309 non-null  int64
 49  dst2src_min_piat_ms           482309 non-null  int64
 50  dst2src_mean_piat_ms          482309 non-null  float64
 51  dst2src_stddev_piat_ms        482309 non-null  float64
 52  dst2src_max_piat_ms           482309 non-null  int64
 53  bidirectional_syn_packets     482309 non-null  int64
 54  bidirectional_cwr_packets     482309 non-null  int64
 55  bidirectional_ece_packets     482309 non-null  int64
 56  bidirectional_urg_packets     482309 non-null  int64
 57  bidirectional_ack_packets     482309 non-null  int64
 58  bidirectional_psh_packets     482309 non-null  int64
 59  bidirectional_rst_packets     482309 non-null  int64
 60  bidirectional_fin_packets     482309 non-null  int64
 61  src2dst_syn_packets           482309 non-null  int64
 62  src2dst_cwr_packets           482309 non-null  int64
 63  src2dst_ece_packets           482309 non-null  int64
 64  src2dst_urg_packets           482309 non-null  int64
 65  src2dst_ack_packets           482309 non-null  int64
 66  src2dst_psh_packets           482309 non-null  int64
 67  src2dst_rst_packets           482309 non-null  int64
 68  src2dst_fin_packets           482309 non-null  int64
 69  dst2src_syn_packets           482309 non-null  int64
 70  dst2src_cwr_packets           482309 non-null  int64
 71  dst2src_ece_packets           482309 non-null  int64
 72  dst2src_urg_packets           482309 non-null  int64
 73  dst2src_ack_packets           482309 non-null  int64
 74  dst2src_psh_packets           482309 non-null  int64
 75  dst2src_rst_packets           482309 non-null  int64
 76  dst2src_fin_packets           482309 non-null  int64
 77  application_name              482309 non-null  object
 78  application_category_name     482309 non-null  object
 79  application_is_guessed        482309 non-null  int64
 80  application_confidence        482309 non-null  int64
 81  requested_server_name         634 non-null     object
 82  client_fingerprint            94 non-null      object
 83  server_fingerprint            45 non-null      object
 84  user_agent                    528 non-null     object
 85  content_type                  141 non-null     object
 86  target                        482309 non-null  object
 87  state                         482309 non-null  object
dtypes: float64(12), int64(61), object(15)
memory usage: 323.8+ MB

In [32]:
data.head()

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,target,state
0,0,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,256,...,Unspecified,0,0,None,None,None,None,None,aggressive-scan,charging
1,1,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,993,...,Email,1,1,None,None,None,None,None,aggressive-scan,charging
2,2,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,139,...,System,1,1,None,None,None,None,None,aggressive-scan,charging
3,3,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,143,...,Email,1,1,None,None,None,None,None,aggressive-scan,charging
4,4,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,135,...,RPC,1,1,None,None,None,None,None,aggressive-scan,charging

In [33]:
data.target.unique()

array(['aggressive-scan', 'benign', 'icmp-flood', 'icmp-fragmentation',
       'os-fingerprinting', 'portscan', 'push-ack-flood',
       'service-detection', 'slowloris-scan', 'syn-flood', 'syn-stealth',
       'synonymous-ip', 'tcp-flood', 'udp-flood', 'vulnerability-scan',
       'syn-stealth-scan'], dtype=object)

In [34]:
data.target.nunique()

16

In [13]:
os.getcwd()

'D:\\bootcamp\\Dos-Project'

## CICIoV

In [45]:
def read_csv_files_in_folder(folder_path):
    """
    Reads CSV files from a folder and concatenates them into a single pandas DataFrame.

    Parameters:
    folder_path (str): Path to the folder containing the CSV files

    Returns:
    pandas.DataFrame: Concatenated DataFrame from all CSV files in the folder
    """
    # Get a list of all CSV files in the folder
    csv_files = [os.path.join(folder_path, f)
                 for f in os.listdir(folder_path) if f.endswith('.csv')]

    # Read each CSV file and append to a list of DataFrames
    dfs = []
    for csv_file in csv_files:
        df = pd.read_csv(csv_file, low_memory=False)
        df['target'] = df['specific_class'].str.lower()
        dfs.append(df)

    # Concatenate the DataFrames into a single DataFrame
    combined_df = pd.concat(dfs, ignore_index=True)

    return combined_df

In [34]:
data = pd.read_parquet('./data/parquets/cicevse_network.parquet')

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482309 entries, 0 to 482308
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            482309 non-null  int64
 1   expiration_id                 482309 non-null  int64
 2   src_ip                        482309 non-null  object
 3   src_mac                       482309 non-null  object
 4   src_oui                       482309 non-null  object
 5   src_port                      482309 non-null  int64
 6   dst_ip                        482309 non-null  object
 7   dst_mac                       482309 non-null  object
 8   dst_oui                       482309 non-null  object
 9   dst_port                      482309 non-null  int64
 10  protocol                      482309 non-null  int64
 11  ip_version                    482309 non-null  int64
 12  vlan_id                       482309 non-null  int64
 13  tunnel_id                     482309 non-null  int64
 14  bidirectional_first_seen_ms   482309 non-null  int64
 15  bidirectional_last_seen_ms    482309 non-null  int64
 16  bidirectional_duration_ms     482309 non-null  int64
 17  bidirectional_packets         482309 non-null  int64
 18  bidirectional_bytes           482309 non-null  int64
 19  src2dst_first_seen_ms         482309 non-null  int64
 20  src2dst_last_seen_ms          482309 non-null  int64
 21  src2dst_duration_ms           482309 non-null  int64
 22  src2dst_packets               482309 non-null  int64
 23  src2dst_bytes                 482309 non-null  int64
 24  dst2src_first_seen_ms         482309 non-null  int64
 25  dst2src_last_seen_ms          482309 non-null  int64
 26  dst2src_duration_ms           482309 non-null  int64
 27  dst2src_packets               482309 non-null  int64
 28  dst2src_bytes                 482309 non-null  int64
 29  bidirectional_min_ps          482309 non-null  int64
 30  bidirectional_mean_ps         482309 non-null  float64
 31  bidirectional_stddev_ps       482309 non-null  float64
 32  bidirectional_max_ps          482309 non-null  int64
 33  src2dst_min_ps                482309 non-null  int64
 34  src2dst_mean_ps               482309 non-null  float64
 35  src2dst_stddev_ps             482309 non-null  float64
 36  src2dst_max_ps                482309 non-null  int64
 37  dst2src_min_ps                482309 non-null  int64
 38  dst2src_mean_ps               482309 non-null  float64
 39  dst2src_stddev_ps             482309 non-null  float64
 40  dst2src_max_ps                482309 non-null  int64
 41  bidirectional_min_piat_ms     482309 non-null  int64
 42  bidirectional_mean_piat_ms    482309 non-null  float64
 43  bidirectional_stddev_piat_ms  482309 non-null  float64
 44  bidirectional_max_piat_ms     482309 non-null  int64
 45  src2dst_min_piat_ms           482309 non-null  int64
 46  src2dst_mean_piat_ms          482309 non-null  float64
 47  src2dst_stddev_piat_ms        482309 non-null  float64
 48  src2dst_max_piat_ms           482309 non-null  int64
 49  dst2src_min_piat_ms           482309 non-null  int64
 50  dst2src_mean_piat_ms          482309 non-null  float64
 51  dst2src_stddev_piat_ms        482309 non-null  float64
 52  dst2src_max_piat_ms           482309 non-null  int64
 53  bidirectional_syn_packets     482309 non-null  int64
 54  bidirectional_cwr_packets     482309 non-null  int64
 55  bidirectional_ece_packets     482309 non-null  int64
 56  bidirectional_urg_packets     482309 non-null  int64
 57  bidirectional_ack_packets     482309 non-null  int64
 58  bidirectional_psh_packets     482309 non-null  int64
 59  bidirectional_rst_packets     482309 non-null  int64
 60  bidirectional_fin_packets     482309 non-null  int64
 61  src2dst_syn_packets           482309 non-null  int64
 62  src2dst_cwr_packets           482309 non-null  int64
 63  src2dst_ece_packets           482309 non-null  int64
 64  src2dst_urg_packets           482309 non-null  int64
 65  src2dst_ack_packets           482309 non-null  int64
 66  src2dst_psh_packets           482309 non-null  int64
 67  src2dst_rst_packets           482309 non-null  int64
 68  src2dst_fin_packets           482309 non-null  int64
 69  dst2src_syn_packets           482309 non-null  int64
 70  dst2src_cwr_packets           482309 non-null  int64
 71  dst2src_ece_packets           482309 non-null  int64
 72  dst2src_urg_packets           482309 non-null  int64
 73  dst2src_ack_packets           482309 non-null  int64
 74  dst2src_psh_packets           482309 non-null  int64
 75  dst2src_rst_packets           482309 non-null  int64
 76  dst2src_fin_packets           482309 non-null  int64
 77  application_name              482309 non-null  object
 78  application_category_name     482309 non-null  object
 79  application_is_guessed        482309 non-null  int64
 80  application_confidence        482309 non-null  int64
 81  requested_server_name         634 non-null     object
 82  client_fingerprint            94 non-null      object
 83  server_fingerprint            45 non-null      object
 84  user_agent                    528 non-null     object
 85  content_type                  141 non-null     object
 86  target                        482309 non-null  object
 87  state                         482309 non-null  object
dtypes: float64(12), int64(61), object(15)
memory usage: 323.8+ MB

In [38]:
data.head().iloc[:,10:]

,protocol,ip_version,vlan_id,tunnel_id,bidirectional_first_seen_ms,bidirectional_last_seen_ms,bidirectional_duration_ms,bidirectional_packets,bidirectional_bytes,src2dst_first_seen_ms,...,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,target,state
0,6,4,0,0,1703261991666,1703261991779,113,2,120,1703261991666,...,Unspecified,0,0,None,None,None,None,None,aggressive-scan,charging
1,6,4,0,0,1703261991667,1703261991784,117,2,120,1703261991667,...,Email,1,1,None,None,None,None,None,aggressive-scan,charging
2,6,4,0,0,1703261991667,1703261991784,117,2,120,1703261991667,...,System,1,1,None,None,None,None,None,aggressive-scan,charging
3,6,4,0,0,1703261991667,1703261991785,118,2,120,1703261991667,...,Email,1,1,None,None,None,None,None,aggressive-scan,charging
4,6,4,0,0,1703261991667,1703261991785,118,2,120,1703261991667,...,RPC,1,1,None,None,None,None,None,aggressive-scan,charging

In [42]:
def read_ciciov(data_path, target):
    '''
    Read parquet file and return the dataset features and target separated.
    '''
    df = pd.read_parquet(data_path)
    x = df.drop(target, axis=1).iloc[:,1:-3]
    y = df[target]
    return x, y

In [46]:
def read_cicevse(data_path, target):
    '''
    Read parquet file and return the dataset features and target separated.
    '''
    df = pd.read_parquet(data_path)
    x = df.drop(target, axis=1).iloc[:,14:-6]
    y = df[target]
    return x, y

In [46]:
def read_data(data_path, target):
    '''
    Read parquet file and return the dataset features and target separated.
    '''
    df = pd.read_parquet(data_path)
    x = df.drop(target, axis=1)
    y = df[target]
    return x, y

In [ ]:
def preprocess_data(X, y, features, batch_size):
    scaler = sklearn.preprocessing.RobustScaler()

    X_scaled = scaler.fit_transform(X[features].values)
    X_tensor = torch.tensor(X_scaled, dtype=torch.float32)
    y_tensor = torch.tensor(y.values, dtype=torch.float32)
    n_features = X_scaled.shape[1]

    dataset = TensorDataset(X_tensor, y_tensor)
    dataloader = DataLoader(dataset, batch_size=train_batch_size, shuffle=True)

    return X_tensor, y_tensor, dataloader

In [56]:
X, Y = read_ciciov('./data/parquets/ciciov.parquet', 'target')

In [57]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408219 entries, 0 to 1408218
Data columns (total 8 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   DATA_0  1408219 non-null  int64
 1   DATA_1  1408219 non-null  int64
 2   DATA_2  1408219 non-null  int64
 3   DATA_3  1408219 non-null  int64
 4   DATA_4  1408219 non-null  int64
 5   DATA_5  1408219 non-null  int64
 6   DATA_6  1408219 non-null  int64
 7   DATA_7  1408219 non-null  int64
dtypes: int64(8)
memory usage: 86.0 MB

In [58]:
Y

0                  benign
1                  benign
2                  benign
3                  benign
4                  benign
                ...
1408214    steering_wheel
1408215    steering_wheel
1408216    steering_wheel
1408217    steering_wheel
1408218    steering_wheel
Name: target, Length: 1408219, dtype: object

In [47]:
X, Y = read_cicevse('./data/parquets/cicevse_network.parquet', 'target')

In [48]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482309 entries, 0 to 482308
Data columns (total 67 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   bidirectional_first_seen_ms   482309 non-null  int64
 1   bidirectional_last_seen_ms    482309 non-null  int64
 2   bidirectional_duration_ms     482309 non-null  int64
 3   bidirectional_packets         482309 non-null  int64
 4   bidirectional_bytes           482309 non-null  int64
 5   src2dst_first_seen_ms         482309 non-null  int64
 6   src2dst_last_seen_ms          482309 non-null  int64
 7   src2dst_duration_ms           482309 non-null  int64
 8   src2dst_packets               482309 non-null  int64
 9   src2dst_bytes                 482309 non-null  int64
 10  dst2src_first_seen_ms         482309 non-null  int64
 11  dst2src_last_seen_ms          482309 non-null  int64
 12  dst2src_duration_ms           482309 non-null  int64
 13  dst2src_packets               482309 non-null  int64
 14  dst2src_bytes                 482309 non-null  int64
 15  bidirectional_min_ps          482309 non-null  int64
 16  bidirectional_mean_ps         482309 non-null  float64
 17  bidirectional_stddev_ps       482309 non-null  float64
 18  bidirectional_max_ps          482309 non-null  int64
 19  src2dst_min_ps                482309 non-null  int64
 20  src2dst_mean_ps               482309 non-null  float64
 21  src2dst_stddev_ps             482309 non-null  float64
 22  src2dst_max_ps                482309 non-null  int64
 23  dst2src_min_ps                482309 non-null  int64
 24  dst2src_mean_ps               482309 non-null  float64
 25  dst2src_stddev_ps             482309 non-null  float64
 26  dst2src_max_ps                482309 non-null  int64
 27  bidirectional_min_piat_ms     482309 non-null  int64
 28  bidirectional_mean_piat_ms    482309 non-null  float64
 29  bidirectional_stddev_piat_ms  482309 non-null  float64
 30  bidirectional_max_piat_ms     482309 non-null  int64
 31  src2dst_min_piat_ms           482309 non-null  int64
 32  src2dst_mean_piat_ms          482309 non-null  float64
 33  src2dst_stddev_piat_ms        482309 non-null  float64
 34  src2dst_max_piat_ms           482309 non-null  int64
 35  dst2src_min_piat_ms           482309 non-null  int64
 36  dst2src_mean_piat_ms          482309 non-null  float64
 37  dst2src_stddev_piat_ms        482309 non-null  float64
 38  dst2src_max_piat_ms           482309 non-null  int64
 39  bidirectional_syn_packets     482309 non-null  int64
 40  bidirectional_cwr_packets     482309 non-null  int64
 41  bidirectional_ece_packets     482309 non-null  int64
 42  bidirectional_urg_packets     482309 non-null  int64
 43  bidirectional_ack_packets     482309 non-null  int64
 44  bidirectional_psh_packets     482309 non-null  int64
 45  bidirectional_rst_packets     482309 non-null  int64
 46  bidirectional_fin_packets     482309 non-null  int64
 47  src2dst_syn_packets           482309 non-null  int64
 48  src2dst_cwr_packets           482309 non-null  int64
 49  src2dst_ece_packets           482309 non-null  int64
 50  src2dst_urg_packets           482309 non-null  int64
 51  src2dst_ack_packets           482309 non-null  int64
 52  src2dst_psh_packets           482309 non-null  int64
 53  src2dst_rst_packets           482309 non-null  int64
 54  src2dst_fin_packets           482309 non-null  int64
 55  dst2src_syn_packets           482309 non-null  int64
 56  dst2src_cwr_packets           482309 non-null  int64
 57  dst2src_ece_packets           482309 non-null  int64
 58  dst2src_urg_packets           482309 non-null  int64
 59  dst2src_ack_packets           482309 non-null  int64
 60  dst2src_psh_packets           482309 non-null  int64
 61  dst2src_rst_packets           482309 non-null  int64
 62  dst2src_fin_packets           482309 non-null  int64
 63  application_name              482309 non-null  object
 64  application_category_name     482309 non-null  object
 65  application_is_guessed        482309 non-null  int64
 66  application_confidence        482309 non-null  int64
dtypes: float64(12), int64(53), object(2)
memory usage: 246.5+ MB

In [51]:
Y

0            aggressive-scan
1            aggressive-scan
2            aggressive-scan
3            aggressive-scan
4            aggressive-scan
                 ...
482304    vulnerability-scan
482305    vulnerability-scan
482306    vulnerability-scan
482307    vulnerability-scan
482308    vulnerability-scan
Name: target, Length: 482309, dtype: object